# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c01fb6f429fbc4bca162c037294019cafd395a89ec0510e570e72c832dae5e94874d5f0c5a4ca358f958c70978a0b6593e5860f031037e1dc87ebb85e61acb0f

test:
  secret_key_base: 23a026abddd5423f464f354bbe23eb4e5b21e0eae1ed318cc98bb7a7eddf0e8881dc46d9323aaf8ef744ebfbbc890cac3845388022ed25eb04efcadfa1c8d84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
